Get http://localhost:3000/hospital/wards

###
GET http://localhost:3000/hospital/wards/5f264c5a72cb5430a034a675


###
POST http://localhost:3000/hospital/wards
Content-Type: application/json

{
    "wardName" : "Cardio",
     "bedCapacity": 5,
    "wardStatus": "active"
}

### Update Ward Details
PATCH http://localhost:3000/hospital/wards/5f26f08aff9b9631e41088cf
Content-Type: application/json

{
    "wardName" : "Cardiolo",
    "bedCapacity": 5,
    "wardStatus": "active"
}

###
DELETE http://localhost:3000/hospital/wards/5f264c5a72cb5430a034a675

###
DELETE http://localhost:3000/hospital/wards

###

### Get Free Beds of Ward
GET http://localhost:3000/hospital/allot-bed/5f275cec15ca9526280a974b

### Allot Bed in Ward
POST http://localhost:3000/hospital/allot-bed
Content-Type: application/json

{
    "patientID" : 1,
    "patientName": "Patient-1",
    "attendentName": "Attendent Name",
    "wardID" : 3,
    "bedID": 4
}

### ROOMS ###

# Add Room
POST http://localhost:3000/hospital/add-room
Content-Type: application/json

{
    "type" : "Normal",
    "details" : "AC"
  
}

### Get Rooms List
GET http://localhost:3000/hospital/rooms


### Edit Room
PATCH http://localhost:3000/hospital/rooms/5f28865384a7d711586f4f7a
Content-Type: application/json

{   
    "type" : "Luxury",
    "details" : " AC",
    "status" : "occupied",
     "patientID" : 1,
    "patientName": "Patient-1-updated",
    "attendentName": "Attendent Updated"
}

### Delete Room by iD
DELETE http://localhost:3000/hospital/rooms/5f28863484a7d711586f4f79

### Delete All Rooms
DELETE http://localhost:3000/hospital/rooms

### Get Rooms that are free
GET http://localhost:3000/hospital/allot-room

### Allot Room
POST  http://localhost:3000/hospital/allot-room
Content-Type: application/json

{   
    "id": 2,
    "patientID" : 1,
    "patientName": "Patient-1-updated",
    "attendentName": "Attendent Updated",
    "allotedFrom": "2014-01-01"
}