GET http://localhost:3000/patients

###

GET http://localhost:3000/patients/profile/5f1e1f242d1f0e2928d88667

###

POST http://localhost:3000/patients/add-patient
Content-Type: application/json

    {   "firstName" : "Patient-2",
         "lastName" : "P",
         "age" : 21,
         "username" : "sk002", 
         "email" : "sk02@gmail.com" ,
         "password" : "pass123",         
         "gender": "male",
         "bloodGroup" : "B+ve",
          "DOB": "\"2014-01-01T23:28:56.782Z\"",
         "address" : "H #112, jsdnsdnjs, Hyd",
         "country" : "Pakistan",
         "city": "Hyd",
         "postalCode" : "71000",
         "phone" : "0900-78601",
         "img" : "assets/img/doctor-01.jpg",
         "details" : "Heart Specialist ...  ",
         "status" : "active"
        
        } 
###

DELETE http://localhost:3000/patients

###

DELETE http://localhost:3000/patients/5f1e1f0b2d1f0e2928d88665

###

PATCH http://localhost:3000/patients/5f1e557c7ae6cc32ec91e0ba
Content-Type: application/json

 {      
        "firstName" : "Stk",
         "lastName" : "Shawn",
         "age" : 30,
         "username" : "sk003", 
         "email" : "sk03@gmail.com" ,
         "password" : "pass123",         
         "gender": "male",
         "DOB": "\"1997-01-01T23:28:56.782Z\"",
         "bloodGroup": "O+ve",
         "address" : "H #112, jsdnsdnjs, Hyd",
         "country" : "Pakistan",
         "city": "Hyd",
         "postalCode" : "71000",
         "phone" : "0900-78601",
         "img" : "assets/img/doctor-01.jpg",
         "details" : "Heart Specialist ...  ",
         "status" : "active"
        
        } 
